# Generated by Django 5.2.7 on 2025-10-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sceehdule',
            new_name='Schedule',
        ),
    ]
