# Generated by Django 5.2.7 on 2025-10-22 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='price',
        ),
    ]
