# Generated by Django 5.2.7 on 2025-10-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_schedule_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='schedules/'),
        ),
    ]
