# Generated by Django 5.2.7 on 2025-10-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_schedule_caption_schedule_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='image',
        ),
        migrations.AddField(
            model_name='schedule',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
