# Generated by Django 5.1.11 on 2025-10-19 07:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, upload_to='fotoUser')),
                ('fakultas', models.CharField(max_length=100)),
            ],
        ),
    ]
