# Generated by Django 5.1.11 on 2025-10-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_fakultas_remove_user_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fakultas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
