# Generated by Django 5.2.7 on 2025-10-23 17:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('ewallet', 'E-Wallet'), ('transfer', 'Transfer Bank'), ('credit', 'Kartu Kredit')], default='ewallet', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('paid', 'Sudah Dibayar')], default='unpaid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='scheduling.schedule')),
            ],
        ),
    ]
