# Generated by Django 5.2.7 on 2025-10-22 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_remove_schedule_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_info', to='scheduling.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.CharField(blank=True, max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('ewallet', 'E-Wallet'), ('transfer', 'Transfer Bank'), ('credit', 'Kartu Kredit')], default='ewallet', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Belum Dibayar'), ('paid', 'Sudah Dibayar')], default='unpaid', max_length=20)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='scheduling.schedule')),
            ],
        ),
    ]
