# Generated by Django 5.2.7 on 2025-10-18 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('t-shirt', 'T-Shirt'), ('sweater', 'Sweater'), ('bandana', 'Bandana'), ('hat', 'Hat'), ('scarf', 'Scarf'), ('totebag', 'Totebag'), ('handfan', 'Handfan'), ('sticker', 'Sticker'), ('keychain', 'Keychain'), ('lanyard', 'Lanyard')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchandises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
