name: Django CI/CD to PBP Server

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from GitHub Secrets
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "PRODUCTION=${{ secrets.PRODUCTION }}" >> .env
          echo "SCHEMA=${{ secrets.SCHEMA }}" >> .env

      - name: Collect static files
        run: python manage.py collectstatic --noinput

      - name: Run database migrations
        run: python manage.py migrate --noinput

      - name: Deploy to PBP server
        run: |
          git remote add production https://pbp.cs.ui.ac.id/adjie.m/oliminate || true
          git push production main --force
